version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cache-resizer-app
    ports:
      - '8080:8080'
    networks:
      - tcc
    volumes:
      - ./db:/app/db
    depends_on:
      - db

  db:
    image: postgres:13.1-alpine
    container_name: tcc_postgres_db
    environment:
      POSTGRES_USER: tccadmin
      POSTGRES_PASSWORD: tccadmin
      POSTGRES_DB: tcc
    ports:
      - "5432:5432"
    volumes:
      - tcc_postgres_data:/var/lib/postgresql/data
    networks:
      - tcc

  haproxy:
    build:
      context: ./docker/haproxy
      dockerfile: Dockerfile
    image: haproxy-tcc:latest
    container_name: haproxy-cache-resizer
    ports:
      - '8100:8100'
      - '8200:8200'
      - '1936:1936'
    volumes:
      - ./docker/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
      - ./docker/haproxy/update-cache.lua:/tmp/update-cache.lua
    command: ["haproxy", "-f", "/usr/local/etc/haproxy/haproxy.cfg", "-p", "/var/run/haproxy.pid", "-x", "/var/run/haproxy.sock"]
    depends_on:
      - app
    networks:
      - tcc

networks:
  tcc:
    driver: bridge

volumes:
  tcc_postgres_data:
    driver: local